version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
  pre_build:
    commands:
      -  echo Entered the pre_build phase...
      -  bash ${CODEBUILD_SRC_DIR}/src/main/resources/scripts/versioning.sh ${CODEBUILD_SRC_DIR}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/app-0.0.1-SNAPSHOT.jar
